In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("../data/raw/student_performance_datasetv1.csv")
df.head()

,student_id,attendance_percentage,quiz_score_avg,assignment_score_avg,midterm_score,historical_gpa,study_hours_per_week,participation_score,subject_difficulty_score,semester_number,final_score,pass_fail
0,510845f3-fec3-423e-84ba-12422f4f8058,78.11,55.80,54.96,59.20,2.31,15.7,75.80,3.74,6,51.65,0
1,85fe2085-7fc6-41a7-9819-9062e3f12102,66.63,69.04,64.40,69.31,3.19,23.5,83.34,5.05,2,69.10,1
2,a1e6e199-b45e-408a-b633-2cc2656dab41,98.21,60.37,57.75,71.17,2.69,15.0,71.54,9.18,4,65.41,1
3,ed75ac0f-5371-4900-b7fa-b59e8978a2ec,79.88,59.76,50.62,44.16,2.34,26.4,72.74,6.13,4,60.38,1
4,2bcfaf42-2ff8-45b6-9975-e8f668e78fe8,66.58,45.49,57.01,49.74,2.12,20.6,72.96,2.27,7,49.10,0

In [23]:
df.isnull().sum()

student_id                  0
attendance_percentage       0
quiz_score_avg              0
assignment_score_avg        0
midterm_score               0
historical_gpa              0
study_hours_per_week        0
participation_score         0
subject_difficulty_score    0
semester_number             0
final_score                 0
pass_fail                   0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.describe()

,attendance_percentage,quiz_score_avg,assignment_score_avg,midterm_score,historical_gpa,study_hours_per_week,participation_score,subject_difficulty_score,semester_number,final_score,pass_fail
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,82.586242,64.731186,64.459905,64.154969,2.951908,22.481620,80.010418,5.526170,4.522000,66.019980,0.766800
std,10.104653,10.420520,10.694330,11.316786,0.491422,4.485954,7.869068,2.602392,2.292022,8.178383,0.422911
min,65.000000,36.552500,35.681250,33.711250,2.000000,8.900000,58.800000,1.000000,1.000000,43.848750,0.000000
25%,73.847500,57.680000,57.210000,56.507500,2.600000,19.100000,74.730000,3.280000,3.000000,60.397500,1.000000
50%,82.435000,64.460000,64.420000,64.350000,2.950000,22.500000,80.045000,5.570000,4.000000,65.860000,1.000000
75%,91.415000,71.765000,71.562500,71.705000,3.290000,25.900000,85.350000,7.780000,7.000000,71.430000,1.000000
max,99.990000,92.892500,93.091250,94.501250,4.000000,34.800000,100.000000,10.000000,8.000000,87.978750,1.000000

In [26]:
##checking the outliers
import pandas as pd
import matplotlib.pyplot as plt



numerical_cols = [
    'attendance_percentage',
    'quiz_score_avg',
    'assignment_score_avg',
    'midterm_score',
    'historical_gpa',
    'study_hours_per_week',
    'participation_score',
    'subject_difficulty_score',
    'semester_number',
    'final_score'
]

for col in numerical_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]

    print(f"{col}: {len(outliers)} outliers")

attendance_percentage: 0 outliers
quiz_score_avg: 0 outliers
assignment_score_avg: 0 outliers
midterm_score: 0 outliers
historical_gpa: 0 outliers
study_hours_per_week: 0 outliers
participation_score: 0 outliers
subject_difficulty_score: 0 outliers
semester_number: 0 outliers
final_score: 0 outliers

In [5]:
df['subject_difficulty_score']= df['subject_difficulty_score']/10

In [6]:
df.head()

,student_id,attendance_percentage,quiz_score_avg,assignment_score_avg,midterm_score,historical_gpa,study_hours_per_week,participation_score,subject_difficulty_score,semester_number,final_score,pass_fail
0,510845f3-fec3-423e-84ba-12422f4f8058,78.11,55.80,54.96,59.20,2.31,15.7,75.80,0.374,6,51.65,0
1,85fe2085-7fc6-41a7-9819-9062e3f12102,66.63,69.04,64.40,69.31,3.19,23.5,83.34,0.505,2,69.10,1
2,a1e6e199-b45e-408a-b633-2cc2656dab41,98.21,60.37,57.75,71.17,2.69,15.0,71.54,0.918,4,65.41,1
3,ed75ac0f-5371-4900-b7fa-b59e8978a2ec,79.88,59.76,50.62,44.16,2.34,26.4,72.74,0.613,4,60.38,1
4,2bcfaf42-2ff8-45b6-9975-e8f668e78fe8,66.58,45.49,57.01,49.74,2.12,20.6,72.96,0.227,7,49.10,0

In [8]:
df.to_csv("../data/processed/student_performance_datasetv2.csv", index=False)